server:
  port: 8805
  
spring:
  application:
    name: campaigns
  datasource:
    url: jdbc:mysql://j3a402.p.ssafy.io:3306/ssafy?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: a402
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      
mybatis:
  type-aliases-package: com.cloud.mapper
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/**/*Mapper.xml
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j3a402.p.ssafy.io:8761/eureka
  instance:
    instance-id: campaigns
    prefer-ip-address: true  # 도커에 올릴때 해줘야 찾음
      
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file: /logging/camapign.log