server:
  port: 8801
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://j3a402.p.ssafy.io:3306/ssafy?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
   service-user:
     path: /user/**
     service-id: user-service
   service-product:
     path: /product/**
     service-id: product-service
   service-auth:
     path: /auth/**
     service-id: auth-center
     sensitive-headers:
      - 
   service-file:
      path: /images/**
      service-id: image-service
      sensitive-headers:
      - 
   service-campaign:
      path: /campaigns/**
      service-id: campaign-service
     
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file: app.log
  
